#!/usr/bin/env python
# -*- coding: utf-8 -*-

# This script is used to combine the splitted npy files generated by
# FDTD.write_field.
#
# usage: combine.py [splitted npy files]

import numpy as np
import sys

fname = sys.argv[1]
head = fname.split('(')[0][:-1]

i_size, j_size, k_size = 0, 0, 0
for fname in sys.argv[1:]:
    string_coordinate = fname.split('(')[1].split(')')[0].split(',')
    i, j, k = map(int, string_coordinate)
    if i > i_size:
        i_size = i
    if j > j_size:
        j_size = j
    if k > k_size:
        k_size = k

i_size += 1
j_size += 1
k_size += 1

data = np.empty((i_size, j_size, k_size), object)
for fname in sys.argv[1:]:
    string_coordinate = fname.split('(')[1].split(')')[0].split(',')
    i, j, k = map(int, string_coordinate)
    data[i,j,k] = np.load(fname)

for i, j in np.ndindex(i_size, j_size):
    for k in range(1, k_size):
        data[i,j,0] = np.dstack(data[i,j,0], data[i,j,k])

data = data[:,:,0]

for i in range(i_size):
    for k in range(1, j_size):
        data[i,0] = np.hstack((data[i,0], data[i,j]))

data = data[:,0]

for i in range(1, i_size):
    data[0] = np.vstack((data[0], data[i]))
    
np.save(head, data[0])
